# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: person.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='person.proto',
  package='person',
  syntax='proto3',
  serialized_pb=_b('\n\x0cperson.proto\x12\x06person\"W\n\rPersonRequest\x12\x11\n\tfirstName\x18\x01 \x01(\t\x12\x10\n\x08lastName\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x12\n\nisEmployee\x18\x04 \x01(\x08\"\x1c\n\x0ePersonResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x32M\n\x0cPersonSender\x12=\n\nSendPerson\x12\x15.person.PersonRequest\x1a\x16.person.PersonResponse\"\x00\x62\x06proto3')
)




_PERSONREQUEST = _descriptor.Descriptor(
  name='PersonRequest',
  full_name='person.PersonRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='firstName', full_name='person.PersonRequest.firstName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lastName', full_name='person.PersonRequest.lastName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='person.PersonRequest.email', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isEmployee', full_name='person.PersonRequest.isEmployee', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=111,
)


_PERSONRESPONSE = _descriptor.Descriptor(
  name='PersonResponse',
  full_name='person.PersonResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ok', full_name='person.PersonResponse.ok', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=141,
)

DESCRIPTOR.message_types_by_name['PersonRequest'] = _PERSONREQUEST
DESCRIPTOR.message_types_by_name['PersonResponse'] = _PERSONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PersonRequest = _reflection.GeneratedProtocolMessageType('PersonRequest', (_message.Message,), dict(
  DESCRIPTOR = _PERSONREQUEST,
  __module__ = 'person_pb2'
  # @@protoc_insertion_point(class_scope:person.PersonRequest)
  ))
_sym_db.RegisterMessage(PersonRequest)

PersonResponse = _reflection.GeneratedProtocolMessageType('PersonResponse', (_message.Message,), dict(
  DESCRIPTOR = _PERSONRESPONSE,
  __module__ = 'person_pb2'
  # @@protoc_insertion_point(class_scope:person.PersonResponse)
  ))
_sym_db.RegisterMessage(PersonResponse)



_PERSONSENDER = _descriptor.ServiceDescriptor(
  name='PersonSender',
  full_name='person.PersonSender',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=143,
  serialized_end=220,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendPerson',
    full_name='person.PersonSender.SendPerson',
    index=0,
    containing_service=None,
    input_type=_PERSONREQUEST,
    output_type=_PERSONRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PERSONSENDER)

DESCRIPTOR.services_by_name['PersonSender'] = _PERSONSENDER

# @@protoc_insertion_point(module_scope)
